version: "3.8"

services:
    mysqldb:
        image: mysql:8.0
        env_file: ./.env
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
            - MYSQL_DATABASE=$MYSQL_DATABASE
        ports:
            - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
        volumes:
            - db-data:/var/lib/mysql
    app:
        depends_on:
            - mysqldb
        build:
            context: .
            dockerfile: Dockerfile
        env_file: ./.env
        ports:
            - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
        environment:
            - DATABASE_URL=$DATABASE_URL
            - JWT_SECRET=$JWT_SECRET
        restart: unless-stopped
volumes:
    db-data:
